cocognite/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from . import settings

urlpatterns = [
    # REQUIRED --------------------------------------------------------- #
    path('admin/', admin.site.urls),
    path('accounts/', include('src.accounts.urls', namespace='accounts')),
    path('accounts/', include('allauth.urls')),

    # PORTALS ---------------------------------------------------------- #
    path('', include('src.website.urls', namespace='website')),
    path('a/', include('src.portals.admins.urls', namespace='admin-portal')),
    path('c/', include('src.portals.customer.urls', namespace='customer-portal')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/accounts/urls.py
from django.urls import path
from .views import CrossAuthView, UserUpdateView

app_name = "accounts"
urlpatterns = [
    path('cross-auth/', CrossAuthView.as_view(), name='cross-auth-view'),
    path('user/change/', UserUpdateView.as_view(), name='user-change'),
]

src/website/urls.py
from django.urls import path
from django.views.generic import TemplateView

app_name = 'website'
urlpatterns = [
    path('', TemplateView.as_view(template_name='website/home.html'), name='home')
]

src/website/templates/website/include/footer.html
{% load static %}
<!-- Footer start -->
<footer class="landing-footer">
    <div class="container">

        <div class="row justify-content-center">

            <div class="col-lg-6 text-center">
                <p class="mb-2">2021 - {% now 'Y' %} © EMS - Designed and Developed by Team
                    <b class="text-danger"><i class="fa fa-sort-alpha-down"></i> Alpha</b>
                </p>
                <p>
                    Event Management System is under-development by team Alpha under the super-vision of Mam Humaira Jabeen
                </p>
            </div>

        </div>
    </div>
    <!-- end container -->
</footer>
<!-- Footer end -->

src/website/templates/website/include/header.html
{% load static %}
<nav class="navbar navbar-expand-lg navigation fixed-top sticky">

    <div class="container">
        <a class="navbar-logo" href="/">
            {# WHITE #}
            <img src="{% static 'core/images/logo_100.png' %}" alt="" height="19" class="logo logo-dark">
            {# COLORED #}
            <img src="{% static 'core/images/logo_100.png' %}" alt="" height="19" class="logo logo-light">
        </a>

        <button type="button" class="btn btn-sm px-3 font-size-16 d-lg-none header-item waves-effect waves-light"
                data-toggle="collapse" data-target="#topnav-menu-content">
            <i class="fa fa-fw fa-bars"></i>
        </button>

        <div class="collapse navbar-collapse" id="topnav-menu-content">
            <ul class="navbar-nav ml-auto" id="topnav-menu">

                <li class="nav-item">
                    <a class="nav-link" href="/#home">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/#roadmap">Roadmap</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/#team">Team</a>
                </li>


            </ul>


            {% if request.user.is_authenticated %}
                <div class="ml-lg-2">
                    <a class="btn btn-sm btn-success" href="{% url 'accounts:cross-auth-view' %}">
                        <i class="mdi mdi-view-dashboard"></i> Dashboard
                    </a>
                </div>
            {% else %}
                <div class="ml-lg-2">
                    <a class="btn btn-sm btn-success" href="{% url 'account_login' %}">
                        <i class="mdi mdi-account-lock"></i> Login
                    </a>
                </div>
            {% endif %}


        </div>
    </div>
</nav>