cocognite/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from . import settings

urlpatterns = [
    # REQUIRED --------------------------------------------------------- #
    path('admin/', admin.site.urls),
    path('accounts/', include('src.accounts.urls', namespace='accounts')),
    path('accounts/', include('allauth.urls')),

    # PORTALS ---------------------------------------------------------- #
    path('', include('src.website.urls', namespace='website')),
    path('a/', include('src.portals.admins.urls', namespace='admin-portal')),
    path('c/', include('src.portals.customer.urls', namespace='customer-portal')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/portals/customer/urls.py
from django.urls import path
from django.views.generic import TemplateView
from .views import (
    EventsListView, EventDetailView, EventCreateView, EventDeleteView, DashboardView, VideoView
)

app_name = "customer-portal"
urlpatterns = [
    path('dashboard', DashboardView.as_view(), name='dashboard'),

    path('event/', EventsListView.as_view(), name='event-list'),
    path('event/<int:pk>/', EventDetailView.as_view(), name='event-detail'),
    path('event/<int:pk>/delete/', EventDeleteView.as_view(), name='event-delete'),
    path('event/add/', EventCreateView.as_view(), name='event-add'),
    path('video/',  VideoView.as_view(), name='view-video'),

]

src/portals/admins/models.py
from django.db import models


class AddOn(models.Model):
    name = models.CharField(max_length=255)
    price = models.FloatField(null=False, blank=False)
    description = models.TextField(null=True, blank=True)

    is_active = models.BooleanField(default=True)

    class Meta:
        verbose_name_plural = 'Add Ons'
        ordering = ['-id']

    def __str__(self):
        return self.name


class EventType(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField(null=True, blank=True)

    is_active = models.BooleanField(default=True)

    class Meta:
        ordering = ['-id']

    def __str__(self):
        return self.name


class Venue(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField(null=True, blank=True)

    is_active = models.BooleanField(default=True)

    class Meta:
        ordering = ['-id']

    def __str__(self):
        return self.name


class Event(models.Model):
    name = models.CharField(max_length=255)
    user = models.ForeignKey('accounts.User', on_delete=models.CASCADE)
    event_type = models.ForeignKey('EventType', on_delete=models.SET_NULL, null=True, blank=False)
    venue = models.ForeignKey('Venue', on_delete=models.SET_NULL, null=True, blank=False)
    add_ons = models.ManyToManyField(AddOn)
    no_of_persons = models.PositiveIntegerField(default=0)
    no_of_chairs = models.PositiveIntegerField(default=100)

    event_charge = models.FloatField(default=1000)
    venue_charge = models.FloatField(default=500)
    tax_charge = models.FloatField(default=100)
    total_charge = models.FloatField(default=0)

    transaction_id = models.CharField(
        max_length=1000, null=False, blank=False,
        help_text="Enter transaction id here, transaction id will be provided by your service provider "
                  "i.e EasyPaisa provide you through sms over a successful transaction", unique=True
    )
    single_split = models.BooleanField(default=False)
    double_split = models.BooleanField(default=False)
    triple_split = models.BooleanField(default=False)
    red_carpet = models.BooleanField(default=False)
    music = models.BooleanField(default=False)

    is_paid = models.BooleanField(default=False)

    is_active = models.BooleanField(default=True)
    created_on = models.DateTimeField(auto_now_add=True)
    event_date = models.DateTimeField()

    class Meta:
        verbose_name_plural = "Events"

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        # _total_charge = self.event_charge + self.venue_charge + self.tax_charge
        # if self.add_ons:
        #     for add_on in self.add_ons.all():
        #         _total_charge += add_on.price
        # self.total_charge = _total_charge
        super(Event, self).save(*args, **kwargs)


class Video(models.Model):
    caption = models.CharField(max_length = 100)
    description = models.TextField()
    video = models.FileField(upload_to = 'videos/', null=True)

    def __str__(self):
        return f'{self.caption}'

src/portals/customer/views.py
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import TemplateView, ListView, DetailView, DeleteView, CreateView
from src.portals.admins.models import Event, Video
from src.portals.customer.bll import calculate_price


class DashboardView(TemplateView):
    template_name = 'customer/dashboard.html'

    def get_context_data(self, **kwargs):
        context = super(DashboardView, self).get_context_data(**kwargs)
        context['events_all'] = Event.objects.filter(user=self.request.user).count()
        context['events_paid'] = Event.objects.filter(user=self.request.user, is_paid=True).count()
        context['events_un_paid'] = Event.objects.filter(user=self.request.user, is_paid=False).count()
        return context


class EventsListView(ListView):
    template_name = 'customer/event_list.html'

    def get_queryset(self):
        return Event.objects.filter(user=self.request.user)


class EventDetailView(DetailView):
    template_name = 'customer/event_detail.html'

    def get_object(self, queryset=None):
        return get_object_or_404(Event.objects.filter(user=self.request.user), pk=self.kwargs['pk'])


class EventDeleteView(DeleteView):
    template_name = 'customer/event_confirm_delete.html'
    model = Event
    success_url = reverse_lazy("customer-portal:event-list")

    def get_object(self, queryset=None):
        return get_object_or_404(Event.objects.filter(user=self.request.user), pk=self.kwargs['pk'])


class EventCreateView(CreateView):
    template_name = 'customer/event_form.html'
    model = Event
    fields = [
        'name', 'event_type', 'venue', 'add_ons', 'no_of_persons',
        'single_split', 'double_split', 'triple_split',
        'red_carpet',  'music', 'event_date', 'transaction_id'
    ]
    success_url = reverse_lazy("customer-portal:event-list")

    def form_valid(self, form):
        # TODO: Calculate according to your pricing setup >>
        calculate_price(form, self.request.user)
        form.instance.user = self.request.user
        return super(EventCreateView, self).form_valid(form)


"""Videos and other video details"""


class VideoView(ListView):
    model = Video
    template_name = 'customer/video_list.html'

src/portals/customer/templates/customer/dashboard.html
{% extends 'core/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block base_title %} {{ request.user }} {% endblock %}

{% block base_links %}{% endblock %}

{% block content %}

    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-body">
                    <div class="row">
                        <div class="col-lg-4">
                            <div class="media">
                                <div class="mr-3">
                                    {% if request.user.profile_image %}
                                        <img src="{{ request.user.profile_image.url }}" alt=""
                                             class="avatar-md rounded-circle img-thumbnail">
                                    {% else %}
                                        <img src="{% static 'images/user.png ' %}" alt=""
                                             class="avatar-md rounded-circle img-thumbnail">
                                    {% endif %}
                                </div>
                                <div class="media-body align-self-center">
                                    <div class="text-muted">
                                        <p class="mb-2">Welcome to Project</p>
                                        <h5 class="mb-1">
                                            {% if request.user.first_name and request.user.last_name %}
                                                {{ request.user.first_name }} {{ request.user_last_name }}
                                            {% else %}
                                                {{ request.user.username }}
                                            {% endif %}
                                        </h5>
                                        <p class="mb-0 text-danger">
                                            Customer Account
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="col-lg-8 align-self-center">
                            <div class="text-lg-center mt-4 mt-lg-0">
                                <div class="row text-center">
                                    <div class="col">
                                        <div>
                                            <h2 class="text-muted mb-0">
                                                <i class="fa fa-clipboard-list"></i>
                                            </h2>
                                            <small>Events</small>
                                            <h5 class="mt-2">{{ events_all }}</h5>
                                        </div>
                                    </div>
                                    <div class="col">
                                        <div>
                                            <h2 class="text-muted mb-0">
                                                <i class="fa fa-clipboard-check"></i>
                                            </h2>
                                            <small>Approved</small>
                                            <h5 class="mt-2">{{ events_paid }}</h5>
                                        </div>
                                    </div>
                                    <div class="col">
                                        <div>
                                            <h2 class="text-muted mb-0">
                                                <i class="fa fa-clipboard"></i>
                                            </h2>
                                            <small>Pending</small>
                                            <h5 class="mb-0">{{ events_un_paid }}</h5>
                                        </div>
                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


{% endblock %}

src/portals/customer/templates/customer/event_confirm_delete.html
{% extends 'core/base.html' %}
{% load static %}

{% block base_title %} Delete {{ object }} {% endblock %}

{% block content %}

    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">

                    <form method="post">{% csrf_token %}
                        <p class="mb-2">Are you sure you want to delete
                            <b class="text-danger">"{{ object }}"</b>
                            ?</p>
                        <input type="submit" class="btn btn-danger" value="Confirm">
                    </form>

                </div>
            </div>
        </div>
    </div>

{% endblock %}

src/portals/customer/templates/customer/event_detail.html
{% extends 'core/base.html' %}
{% load static %}

{% block base_title %} {{ object }} {% endblock %}

{% block content %}

    <div class="row">

        {# LEFT SIDE #}
        <div class="col-md-8">
            <div class="card">
                <div class="card-header bg-white border-bottom">
                    <p class="mb-0 card-title">Event Information</p>
                </div>
                <div class="card-body">

                    <div class="text-center">
                        <p class="h3 mb-0">{{ object.name }}</p>
                        <p class="text-primary">
                            {% for add_on in object.add_ons.all %}
                                <b>{{ add_on }}</b> -
                            {% endfor %}
                        </p>
                    </div>

                    <div class="row justify-content-center text-center my-4">

                        <div class="col">
                            <h1>
                                <i class="fa fa-sort"></i>
                            </h1>
                            <p class="mb-0">Event Type</p>
                            <h5 class="mb-0">{{ object.event_type }}</h5>
                        </div>

                        <div class="col">
                            <h1>
                                <i class="fa fa-hotel"></i>
                            </h1>
                            <p class="mb-0">Venue</p>
                            <h5 class="mb-0">{{ object.venue }}</h5>
                        </div>

                        <div class="col">
                            <h1>
                                <i class="fa fa-users"></i>
                            </h1>
                            <p class="mb-0">Guests</p>
                            <h5 class="mb-0">{{ object.no_of_persons }}</h5>
                        </div>

                    </div>

                </div>
            </div>
        </div>

        {# RIGHT SIDE #}
        <div class="col-md-4">
            <div class="card">
                <div class="card-header bg-white border-bottom">
                    <p class="mb-0 card-title">Payment and Budget</p>
                </div>
                <div class="card-body">

                    {% if object.is_paid %}
                        <p class="bg-success text-white p-2"><i class="fa fa-check-circle"></i>
                            Payment is verified by administration
                        </p>
                    {% else %}
                        <p class="bg-danger text-white p-2"><i class="fa fa-times-circle"></i>
                            Payment is not verified by administration
                        </p>
                    {% endif %}

                     <div class="table-responsive">
                         <table class="table table-borderless table-sm">
                             <tr>
                                 <th>Event Charge</th>
                                 <td>{{ object.event_charge }}</td>
                             </tr>
                             <tr>
                                 <th>Venue Charge</th>
                                 <td>{{ object.venue_charge }}</td>
                             </tr>
                             <tr>
                                 <th>Tax Charge</th>
                                 <td>{{ object.tax_charge }}</td>
                             </tr>
                             <tr>
                                 <th>Total Charge</th>
                                 <td>{{ object.total_charge }}</td>
                             </tr>
                         </table>
                     </div>

                </div>
            </div>
        </div>
    </div>

    <div class="row">
    <div class="col-12">
        <p><b><a href="{% url 'customer-portal:event-list' %}"> -- Back to My Booking</a></b></p>
    </div>
    </div>

{% endblock %}

src/portals/customer/templates/customer/event_form.html
{% extends 'core/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block base_title %}New Event{% endblock %}

{% block page_heading %}
    New Event
{% endblock %}

{% block base_links %}
    <!-- XDSoft DateTimePicker -->
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.min.css"
          integrity="sha256-DOS9W6NR+NFe1fUhEE0PGKY/fubbUCnOfTje2JMDw3Y=" crossorigin="anonymous"/>
{% endblock %}

{% block content %}
    <div class="row justify-content-center">

        <div class="card col-6">
            <div class="card-header bg-danger">
                <h3 class="text-light"><i class="fa fa-exclamation-triangle"></i> NOTICE</h3>
            </div>

            <div class="card-body">
                <p class="">Please follow the guide lines below for successful booking and safe payment.</p>
                <ol>
                    <li>Enter event <b>Name</b> of your choice</li>
                    <li>Select <b>Event Type</b></li>
                    <li>Select <b>Venue</b></li>
                    <li>Select <b>Add-Ons</b> according to your requirements, your can select multiple as well</li>
                    <li>No of expected <b>Guests</b></li>
                    <li>Event <b>Date</b> and <b>Time</b></li>
                    <li>After filling form - pay amount of
                        <b class="text-danger"><i class="fa fa-dollar"></i> Rs 1000</b>
                        with easypaise to account: <b class="text-primary">+92 340 00 00 000</b>
                    </li>
                    <li>On successful transaction, copy the <b class="text-primary">transaction id</b>
                        provided by easypaisa (SMS)
                    </li>
                    <li>Paste this id in transaction_id field (Last One) and submit your form.</li>
                    <li>Wait for 24 hours, it will be updated, if in case any issues please contact</li>
                    
                </ol>
            </div>
        </div>
    </div>

    <div class="row justify-content-center">

        <div class="card col-6">
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    {{ form.media }}
                    {{ form| crispy }}
                    <button class="btn btn-success" type="submit"><i class="fa fa-check"></i> Submit</button>
                </form>
                <div class="mt-3">
                    <a href="{% url 'customer-portal:event-list' %}"><i class="fa fa-arrow-left"></i> Back to List</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}


{% block base_internal_scripts %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.full.min.js"
            integrity="sha256-FEqEelWI3WouFOo2VWP/uJfs1y8KJ++FLh2Lbqc8SJk=" crossorigin="anonymous"></script>

{% endblock %}


{% block base_external_scripts %}
    <script>
        $(document).ready(function () {

            $('#id_event_date').datetimepicker({
                format: 'Y-m-d H:i:s',
            });

        });
    </script>
{% endblock %}

src/portals/customer/templates/customer/event_list.html
{% extends 'core/base.html' %}
{% load static %}

{% block base_title %} My Events {% endblock %}
{% block page_heading %}
    My Events
{% endblock %}

{% block base_links %}
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.22/css/jquery.dataTables.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.6.5/css/buttons.dataTables.min.css">
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-6">
            <div class="mb-2">
                <a href="{% url 'customer-portal:event-add' %}" class="btn btn-primary">
                    <i class="fa fa-plus"></i> Create Event
                </a>
            </div>
            </div>
            <div class=" col-6 mb-2 text-right">
                
                <a href="{% url 'customer-portal:view-video' %}" class="btn btn-primary">
                    
                     View Demo Videos
                </a>
            </div>
        </div>

<div>
    
</div>
 <div class="row">
     <div class="col-12">
        <div class="card ">
            <div class="card-body">
                {% if event_list %}
                    <div class="table-responsive">
                        <table class="table table-hover table-striped">
                            <thead>
                            <tr>
                                <th>Name</th>
                                <th>User</th>
                                <th>Type</th>
                                <th>Venue</th>
                                <th>Add On</th>
                                <th>Music</th>
                                <th>Tx ID</th>
                                <th>Created On</th>
                                <th>Payment</th>
                                <th></th>
                            </tr>
                            </thead>
                            <tbody class="">
    
                            {% for row in event_list %}
                                <tr>
                                    <td>{{ row.name }}</td>
                                    <td>{{ row.user }}</td>
                                    <td>{{ row.event_type }}</td>
                                    <td>{{ row.venue }}</td>
                                    <td>
                                        {% for add_on in row.add_ons.all %}
                                            <span class="badge badge-pill badge-soft-primary font-size-12">{{ add_on.name }}</span>
                                        {% endfor %}
    
                                    </td>
                                    <td>{{ row.transaction_id }}</td>
                                    <td>{{ row.created_on }}</td>
                                    <td>
                                        {% if row.is_paid %}
                                            <b class="text-success">
                                                <a href="#">
                                                    <i class="fa fa-check-circle"></i> Verified
                                                </a>
                                            </b>
                                        {% else %}
                                            <b>
                                                <a href="#" class="text-danger">
                                                    <i class="fa fa-times-circle"></i> Not Verified
                                                </a>
                                            </b>
                                        {% endif %}
                                    </td>
                                    <td>
                                        <a href="{% url 'customer-portal:event-detail' row.pk %}">
                                            <i class="fa fa-eye"></i></a>
                                        <a class="text-danger"
                                           href="{% url 'customer-portal:event-delete' row.pk %}">
                                            <i class="fa fa-trash"></i></a>
                                    </td>
                                </tr>
    
                            {% endfor %}
    
    
                            </tbody>
                        </table>
                    </div>
                {% else %}
                    <p>
                    <h5 class="card-title text-danger">No event orders placed yet.</h5>
                    </p>
    
                {% endif %}
            </div>
        </div>
    
     </div>
 </div>

{% endblock %}

{% block base_internal_scripts %}

    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.5/js/dataTables.buttons.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.5/js/buttons.flash.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.5/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.5/js/buttons.print.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.5/js/buttons.colVis.min.js"></script>


{% endblock %}

{% block base_external_scripts %}
    <script>
        $(document).ready(function () {
            $('table').DataTable({
                dom: 'Bfrtip',
                buttons: [
                    {
                        extend: 'colvis',
                        exportOptions: {
                            columns: ':visible'
                        },
                        text: 'Show/Hide',
                        titleAttr: 'Column Visibility'
                    },
                    {
                        extend: 'copy',
                        exportOptions: {
                            columns: ':visible'
                        },
                        text: '<i class="fa fa-copy text-dark"></i>',
                        titleAttr: 'Copy'
                    },
                    {
                        extend: 'excel',
                        exportOptions: {
                            columns: ':visible'
                        },
                        text: '<i class="fa fa-file-excel-o text-success"></i>',
                        titleAttr: 'Excel'
                    },
                    {
                        extend: 'csv',
                        exportOptions: {
                            columns: ':visible'
                        },
                        text: '<i class="fa fa-file text-success"></i>',
                        titleAttr: 'CSV'
                    },
                    {
                        extend: 'pdf',
                        exportOptions: {
                            columns: ':visible'
                        },
                        text: '<i class="fa fa-file-pdf text-danger"></i>',
                        titleAttr: 'PDF'
                    },
                    {
                        extend: 'print',
                        exportOptions: {
                            columns: ':visible'
                        },
                        text: '<i class="fa fa-print text-primary"></i>',
                        titleAttr: 'Print'
                    }
                ]
            })
            ;

        });

    </script>
{% endblock %}

src/portals/customer/templates/customer/video_list.html
{% extends 'core/base.html' %}
{% load static %}

{% block base_title %} My Events {% endblock %}
{% block page_heading %}
   Demo Videos
{% endblock %}



{% block content %}
<div class="row">
    {% for item in video_list %}
    <div class="col-4">
        <div class="card">
            <div class="card-body">
                <div class="card-text">
                    <h3 class="text-center mt-2 mb-2">{{item.caption}}</h3>
                    <video class="embed-responsive embed-responsive-16by9" controls="controls">
                    <source  src="{{item.video.url}}"/>
                </video>
                <p class="text-center mt-2 mb-2">{{item.description}}</p>
                </div>
            </div>
        </div>
       
    </div>
    {% endfor %}
</div>


{% endblock %}