cocognite/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from . import settings

urlpatterns = [
    # REQUIRED --------------------------------------------------------- #
    path('admin/', admin.site.urls),
    path('accounts/', include('src.accounts.urls', namespace='accounts')),
    path('accounts/', include('allauth.urls')),

    # PORTALS ---------------------------------------------------------- #
    path('', include('src.website.urls', namespace='website')),
    path('a/', include('src.portals.admins.urls', namespace='admin-portal')),
    path('c/', include('src.portals.customer.urls', namespace='customer-portal')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/accounts/urls.py
from django.urls import path
from .views import CrossAuthView, UserUpdateView

app_name = "accounts"
urlpatterns = [
    path('cross-auth/', CrossAuthView.as_view(), name='cross-auth-view'),
    path('user/change/', UserUpdateView.as_view(), name='user-change'),
]

templates/core/base.html
{% load static %}
{#{% load notifications_tags %}#}
<!doctype html>
<html lang="en">
<head>
    <link rel="icon" href="{% static "core/images/favicon.ico" %}">
    <title>EMS |

        {# BASE HALF TITLE #}
        {% block base_title %}{% endblock %}
        {# --------------- #}

    </title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

{#    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">#}
{#    <link rel="stylesheet" href="{% static 'application/css/app-dark.min.css' %}">#}
{#    <link rel="stylesheet" href="{% static 'application/css/bootstrap-dark.min.css' %}">#}

    <link rel="stylesheet" href="{% static 'core/css/app.min.css' %}">
    <link rel="stylesheet" href="{% static 'core/css/bootstrap.min.css' %}">

    <link rel="stylesheet" href="{% static 'core/css/icons.min.css' %}">


    {# BASE LINKS THAT ARE REQUIRED FOR CERTAIN PAGE ------------- #}
    {% block base_links %}

    {% endblock %}
    {# ----------------------------------------------------------- #}

</head>
<body data-topbar="dark" data-layout="horizontal">

<!-- Begin page -->
<div id="layout-wrapper">

    {# BASE TOP NAVIGATION PANEL AREA -------------------------- #}
    {% block base_top_nav %}
        {% include 'core/base_head.html' %}
    {% endblock %}
    {# --------------------------------------------------------- #}

    {% block dont_include_details %}

        <div class="main-content">

            <div class="page-content mt-4">
                <div class="container-fluid mt-5">

                    <div class="row">
                        {% include 'core/include/message.html' %}
                    </div>

                    <!-- start page title -->
                    <div class="row">
                        <div class="col-12">
                            <div class="page-title-box d-flex align-items-center justify-content-between">
                                <h4 class="mb-0 font-size-18">

                                    {% block page_heading %} {% endblock %}</h4>

                            </div>
                        </div>
                    </div>
                    <!-- end page title -->

                    <div class="row">
                        <div class="col-12">
                            {% block content %}

                            {% endblock %}
                        </div>
                    </div>
                </div>
            </div>
        </div>


    {% endblock %}
</div>
<script src="{% static 'js/helper.js' %}"></script>

<script src="{% static 'core/libs/jquery/jquery.min.js' %}"></script>
<script src="{% static 'core/libs/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'core/libs/metismenu/metisMenu.min.js' %}"></script>
<script src="{% static 'core/libs/simplebar/simplebar.min.js' %}"></script>
<script src="{% static 'core/libs/node-waves/waves.min.js' %}"></script>
<script src="{% static 'js/moment.js' %}"></script>
<script src="{% static 'core/js/app.js' %}"></script>



{#<script src="{% static 'js/notify.js' %}" type="text/javascript"></script>#}
{#{% register_notify_callbacks callbacks='fill_notification_badge,my_special_notification_callback' %}#}


{# BASE INTERNAL SCRIPTS OR LINKS THAT ARE REQUIRED IN PAGE #}
{% block base_internal_scripts %}

{% endblock %}
{# -------------------------------------------------------- #}

</body>
</html>


{# BASE EXTERNAL SCRIPTS OR LINKS THAT ARE REQUIRED IN PAGE #}
{% block base_external_scripts %}

{% endblock %}
{# -------------------------------------------------------- #}

templates/core/base_head.html
{% load static %}
{#{% load notifications_tags %}#}

{# MAIN HEADER ------------------------------------------------------------------------------------------------------ #}
<header id="page-topbar">
    <div class="navbar-header">

        {# LEFT HEAD ------------------- #}
        <div class="d-flex">
            <div class="navbar-brand-box">
                <a href="/" class="logo logo-dark">
                    <span class="logo-sm">
                        <img src="{% static 'core/images/logo_100.png' %}" alt="" height="22">
                    </span>
                    <span class="logo-lg">
                        <img src="{% static 'core/images/logo_100.png' %}" alt="" height="17">
                    </span>
                </a>

                <a href="/" class="logo logo-light">
                    <span class="logo-sm">
                        <img src="{% static 'core/images/logo_100.png' %}" alt="" height="22">
                    </span>
                    <span class="logo-lg">
                        <img src="{% static 'core/images/logo_100.png' %}" alt="" height="19">
                    </span>
                </a>
            </div>

            <button type="button" class="btn btn-sm px-3 font-size-16 d-lg-none header-item waves-effect waves-light"
                    data-toggle="collapse" data-target="#topnav-menu-content">
                <i class="fa fa-fw fa-bars"></i>
            </button>

        </div>

        {# RIGHT HEAD ------------------ #}
        <div class="d-flex">

            {# FULL_SCREEN -------------------------------------------------------- #}

            <div class="dropdown d-none d-lg-inline-block ml-1">
                <button type="button" class="btn header-item noti-icon waves-effect" data-toggle="fullscreen">
                    <i class="bx bx-fullscreen"></i>
                </button>
            </div>

            {# NOTIFICATIONS ------------------------------------------------------ #}

            <div class="dropdown d-inline-block">
                <button type="button" class="btn header-item noti-icon waves-effect"
                        id="page-header-notifications-dropdown"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="bx bx-bell bx-tada"></i>
                    <span class="badge badge-danger badge-pill">
                        1
{#                        % live_notify_badge %}#}
                    </span>
                </button>
                <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right p-0"
                     aria-labelledby="page-header-notifications-dropdown">
                    <div class="p-3">
                        <div class="row align-items-center">
                            <div class="col">
                                <h6 class="m-0"> Notifications </h6>
                            </div>
                            <div class="col-auto">
                                <a href="#" class="small"> View All</a>
                            </div>
                        </div>
                    </div>
                    <div data-simplebar style="max-height: 230px;">
                        <div id="notify_me_now">

                        </div>
                        <div class="p-2 border-top text-center">
                            <button class="btn text-primary small">
                                <i class="mdi mdi-arrow-right-circle mr-1"></i> Mark All as Read
                            </button>
                        </div>
                    </div>
                </div>

            </div>

            {# USER ONLINE -------------------------------------------------------- #}

            <div class="dropdown d-inline-block">
                <button type="button" class="btn header-item waves-effect" id="page-header-user-dropdown"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">

                    {% if request.user.profile_image %}
                        <img class="rounded-circle header-profile-user" src="{% static 'images/user.png' %}" alt="Header Avatar">
                    {% else %}
                         <img class="rounded-circle header-profile-user" src="{% static 'images/user.png' %}">
                    {% endif %}


                    <span class="d-none d-xl-inline-block ml-1">{{ request.user.username }}</span>
                    <i class="mdi mdi-chevron-down d-none d-xl-inline-block"></i>
                </button>
                <div class="dropdown-menu dropdown-menu-right">
                    <a class="dropdown-item" href="{% url 'accounts:user-change' %}">
                        <i class="bx bx-user font-size-16 align-middle mr-1"></i> Profile
                    </a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item d-block text-danger" href="#">
                        {#                        <span class="badge badge-success float-right">11</span>#}
                        <i class="bx bx-wrench font-size-16 align-middle mr-1"></i> Settings
                    </a>
                    <a class="dropdown-item" href="{% url 'account_email' %}">
                        <i class="bx bxl-telegram font-size-16 align-middle mr-1"></i> Email accounts
                    </a>
                    <a class="dropdown-item" href="{% url 'account_change_password' %}">
                        <i class="bx bx-lock-open font-size-16 align-middle mr-1"></i>Password Change
                    </a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item text-primary" href="{% url 'account_logout' %}">
                        <i class="bx bx-power-off font-size-16 align-middle mr-1"></i> Logout
                    </a>
                </div>
            </div>

            {# USER INFO ---------------------------------------------------------- #}

        </div>

    </div>
</header>

{# SUB HEADER ------------------------------------------------------------------------------------------------------- #}
<div class="topnav">
    <div class="container-fluid">
        <nav class="navbar navbar-light navbar-expand-lg topnav-menu">

            <div class="collapse navbar-collapse" id="topnav-menu-content">
                <ul class="navbar-nav">

                    {% if request.user.is_authenticated %}
                        {% if request.user.is_superuser %}
                            {% include 'core/include/admin_header.html' %}
                        {% elif request.user.is_staff %}
                            {% include 'core/include/organizer_header.html' %}
                        {% else %}
                            {% include 'core/include/customer_header.html' %}
                        {% endif %}
                    {% endif %}

                </ul>
            </div>
        </nav>
    </div>
</div>