cocognite/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from . import settings

urlpatterns = [
    # REQUIRED --------------------------------------------------------- #
    path('admin/', admin.site.urls),
    path('accounts/', include('src.accounts.urls', namespace='accounts')),
    path('accounts/', include('allauth.urls')),

    # PORTALS ---------------------------------------------------------- #
    path('', include('src.website.urls', namespace='website')),
    path('a/', include('src.portals.admins.urls', namespace='admin-portal')),
    path('c/', include('src.portals.customer.urls', namespace='customer-portal')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/portals/admins/urls.py
from django.urls import path, include
from django.views.generic import TemplateView
from .views import (
    AddonListView, AddonCreateView, AddonUpdateView, AddonDeleteView,
    EventTypeListView, EventTypeCreateView, EventTypeUpdateView, EventTypeDeleteView,
    VenueListView, VenueCreateView, VenueUpdateView, VenueDeleteView,
    EventListView, EventDetailView, EventUpdateView, EventDeleteView,
    PaymentVerificationEasyPaisa, DashboardView)

app_name = "admin-portal"
urlpatterns = [
    path('dashboard/', DashboardView.as_view(), name='dashboard'),

    path('addon/', AddonListView.as_view(), name='addon-list-view'),
    path('addon/add/', AddonCreateView.as_view(), name='addon-create-view'),
    path('addon/<int:pk>/change/', AddonUpdateView.as_view(), name='addon-update-view'),
    path('addon/<int:pk>/delete/', AddonDeleteView.as_view(), name='addon-delete-view'),

    path('eventtype/', EventTypeListView.as_view(), name='eventtype-list-view'),
    path('eventtype/add/', EventTypeCreateView.as_view(), name='eventtype-create-view'),
    path('eventtype/<int:pk>/change/', EventTypeUpdateView.as_view(), name='eventtype-update-view'),
    path('eventtype/<int:pk>/delete/', EventTypeDeleteView.as_view(), name='eventtype-delete-view'),

    path('venue/', VenueListView.as_view(), name='venue-list-view'),
    path('venue/add/', VenueCreateView.as_view(), name='venue-create-view'),
    path('venue/<int:pk>/change/', VenueUpdateView.as_view(), name='venue-update-view'),
    path('venue/<int:pk>/delete/', VenueDeleteView.as_view(), name='venue-delete-view'),

    path('event/', EventListView.as_view(), name='event-list-view'),
    path('event/<int:pk>/', EventDetailView.as_view(), name='event-detail-view'),
    path('event/<int:pk>/change/', EventUpdateView.as_view(), name='event-update-view'),
    path('event/<int:pk>/delete/', EventDeleteView.as_view(), name='event-delete-view'),



    path(
        'payment/verification/easypaisa/',
        PaymentVerificationEasyPaisa.as_view(),
        name='payment-verification-easypaisa'
    )

]

src/portals/admins/templates/admins/addon_confirm_delete.html
{% extends 'core/base.html' %}
{% load static %}

{% block base_title %} Delete {{ object }} {% endblock %}

{% block content %}

    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">

                    <form method="post">{% csrf_token %}
                        <p class="mb-2">Are you sure you want to delete
                            <b class="text-danger">"{{ object }}"</b>
                            ?</p>
                        <input type="submit" class="btn btn-danger" value="Confirm">
                    </form>

                </div>
            </div>
        </div>
    </div>

{% endblock %}

src/portals/admins/templates/admins/addon_form.html
{% extends 'core/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block base_title %}Add/Update AddOn{% endblock %}

{% block page_heading %}
    Add/Update AddOn
{% endblock %}

{% block content %}
    <div class="row justify-content-center">

        <div class="card col-sm-10">
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    {{ form.media }}
                    {{ form| crispy }}
                    <button class="btn btn-success" type="submit"><i class="fa fa-check"></i> Submit</button>
                </form>
                <div class="mt-3">
                    <a href="{% url 'admin-portal:addon-list-view' %}"><i class="fa fa-arrow-left"></i> Back to List</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

src/portals/admins/templates/admins/addon_list.html
{% extends 'core/base.html' %}
{% load static %}

{% block base_title %} Add Ons {% endblock %}
{% block page_heading %}
    Add Ons
{% endblock %}

{% block base_links %}
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.22/css/jquery.dataTables.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.6.5/css/buttons.dataTables.min.css">
{% endblock %}

{% block content %}

    <div class="mb-2">
        <a href="{% url 'admin-portal:addon-create-view' %}" class="btn btn-primary">
            <i class="fa fa-plus"></i> Add AddOn
        </a>
    </div>

    <div class="card">
        <div class="card-body">
            {% if addon_list %}
                <div class="table-responsive">
                    <table class="table table-hover table-striped">
                        <thead>
                        <tr>
                            <th>ID</th>
                            <th>Name</th>
                            <th>Price</th>
                            <th>Status</th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody class="">

                        {% for row in addon_list %}
                            <tr>
                                <td>{{ row.pk }}</td>
                                <td>{{ row.name }}</td>
                                <td>{{ row.price }}</td>
                                <td>
                                    {% if row.is_active %}
                                        <i class="fa fa-check text-success"></i>
                                    {% else %}
                                        <i class="fa fa-times text-danger"></i>
                                    {% endif %}
                                </td>
                                <td>
                                    <a href="{% url 'admin-portal:addon-update-view' row.pk %}">
                                        <i class="fa fa-edit"></i></a>
                                    <a class="text-danger"
                                       href="{% url 'admin-portal:addon-delete-view' row.pk %}">
                                        <i class="fa fa-trash"></i></a>
                                </td>
                            </tr>

                        {% endfor %}


                        </tbody>
                    </table>
                </div>
            {% else %}
                <p>
                <h5 class="card-title text-danger">No Add On's added by administration.</h5>
                </p>

            {% endif %}
        </div>
    </div>

{% endblock %}

{% block base_internal_scripts %}

    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.5/js/dataTables.buttons.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.5/js/buttons.flash.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.5/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.5/js/buttons.print.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.5/js/buttons.colVis.min.js"></script>


{% endblock %}

{% block base_external_scripts %}
    <script>
        $(document).ready(function () {
            $('table').DataTable({
                dom: 'Bfrtip',
                buttons: [
                    {
                        extend: 'colvis',
                        exportOptions: {
                            columns: ':visible'
                        },
                        text: 'Show/Hide',
                        titleAttr: 'Column Visibility'
                    },
                    {
                        extend: 'copy',
                        exportOptions: {
                            columns: ':visible'
                        },
                        text: '<i class="fa fa-copy text-dark"></i>',
                        titleAttr: 'Copy'
                    },
                    {
                        extend: 'excel',
                        exportOptions: {
                            columns: ':visible'
                        },
                        text: '<i class="fa fa-file-excel-o text-success"></i>',
                        titleAttr: 'Excel'
                    },
                    {
                        extend: 'csv',
                        exportOptions: {
                            columns: ':visible'
                        },
                        text: '<i class="fa fa-file text-success"></i>',
                        titleAttr: 'CSV'
                    },
                    {
                        extend: 'pdf',
                        exportOptions: {
                            columns: ':visible'
                        },
                        text: '<i class="fa fa-file-pdf text-danger"></i>',
                        titleAttr: 'PDF'
                    },
                    {
                        extend: 'print',
                        exportOptions: {
                            columns: ':visible'
                        },
                        text: '<i class="fa fa-print text-primary"></i>',
                        titleAttr: 'Print'
                    }
                ]
            })
            ;

        });

    </script>
{% endblock %}

src/portals/admins/templates/admins/event_form.html
{% extends 'core/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block base_title %}Update Event{% endblock %}

{% block page_heading %}
    Update event
{% endblock %}

{% block content %}
    <div class="row justify-content-center">

        <div class="card col-sm-8">
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    {{ form.media }}
                    {{ form| crispy }}
                    <button class="btn btn-success" type="submit"><i class="fa fa-check"></i> Submit</button>
                </form>
                <div class="mt-3">
                    <a href="{% url 'admin-portal:event-list-view' %}"><i class="fa fa-arrow-left"></i> Back to List</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

src/portals/admins/templates/admins/event_list.html
{% extends 'core/base.html' %}
{% load static %}

{% block base_title %} Events {% endblock %}
{% block page_heading %}
    Events
{% endblock %}

{% block base_links %}
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.22/css/jquery.dataTables.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.6.5/css/buttons.dataTables.min.css">
{% endblock %}

{% block content %}


    <div class="card">
        <div class="card-body">
            {% if event_list %}
                <div class="table-responsive">
                    <table class="table table-hover table-striped">
                        <thead>
                        <tr>
                            <th>Name</th>
                            <th>User</th>
                            <th>Type</th>
                            <th>Venue</th>
                            <th>Add On</th>
                            <th>Tx ID</th>
                            <th>Created On</th>
                            <th>Payment</th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody class="">

                        {% for row in event_list %}
                            <tr>
                                <td>{{ row.name }}</td>
                                <td>{{ row.user }}</td>
                                <td>{{ row.event_type }}</td>
                                <td>{{ row.venue }}</td>
                                <td>
                                    {% for add_on in row.add_ons.all %}
                                        <span class="badge badge-pill badge-soft-primary font-size-12">{{ add_on.name }}</span>
                                    {% endfor %}

                                </td>
                                <td>{{ row.transaction_id }}</td>
                                <td>{{ row.created_on }}</td>
                                <td>
                                    {% if row.is_paid %}
                                        <b class="text-success">
                                            <a href="#">
                                                <i class="fa fa-check-circle"></i> Verified
                                            </a>
                                        </b>
                                    {% else %}
                                        <b>
                                            <a href="#" class="text-danger">
                                                <i class="fa fa-times-circle"></i> Not Verified
                                            </a>
                                        </b>
                                    {% endif %}
                                </td>
                                <td>
                                    {#                                    <a href="{% url 'admin-portal:event-detail-view' row.pk %}">#}
                                    {#                                        <i class="fa fa-eye"></i></a>#}
                                    <a href="{% url 'admin-portal:event-update-view' row.pk %}">
                                        <i class="fa fa-edit"></i></a>
                                    <a class="text-danger"
                                       href="{% url 'admin-portal:event-delete-view' row.pk %}">
                                        <i class="fa fa-trash"></i></a>
                                </td>
                            </tr>

                        {% endfor %}


                        </tbody>
                    </table>
                </div>
            {% else %}
                <p>
                <h5 class="card-title text-danger">No event orders placed yet.</h5>
                </p>

            {% endif %}
        </div>
    </div>


{% endblock %}

{% block base_internal_scripts %}

    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.5/js/dataTables.buttons.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.5/js/buttons.flash.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.5/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.5/js/buttons.print.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.5/js/buttons.colVis.min.js"></script>


{% endblock %}

{% block base_external_scripts %}
    <script>
        $(document).ready(function () {
            $('table').DataTable({
                dom: 'Bfrtip',
                buttons: [
                    {
                        extend: 'colvis',
                        exportOptions: {
                            columns: ':visible'
                        },
                        text: 'Show/Hide',
                        titleAttr: 'Column Visibility'
                    },
                    {
                        extend: 'copy',
                        exportOptions: {
                            columns: ':visible'
                        },
                        text: '<i class="fa fa-copy text-dark"></i>',
                        titleAttr: 'Copy'
                    },
                    {
                        extend: 'excel',
                        exportOptions: {
                            columns: ':visible'
                        },
                        text: '<i class="fa fa-file-excel-o text-success"></i>',
                        titleAttr: 'Excel'
                    },
                    {
                        extend: 'csv',
                        exportOptions: {
                            columns: ':visible'
                        },
                        text: '<i class="fa fa-file text-success"></i>',
                        titleAttr: 'CSV'
                    },
                    {
                        extend: 'pdf',
                        exportOptions: {
                            columns: ':visible'
                        },
                        text: '<i class="fa fa-file-pdf text-danger"></i>',
                        titleAttr: 'PDF'
                    },
                    {
                        extend: 'print',
                        exportOptions: {
                            columns: ':visible'
                        },
                        text: '<i class="fa fa-print text-primary"></i>',
                        titleAttr: 'Print'
                    }
                ]
            })
            ;

        });

    </script>
{% endblock %}

src/portals/admins/templates/admins/eventtype_form.html
{% extends 'core/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block base_title %}Add/Update Event Type{% endblock %}

{% block page_heading %}
    Add/Update Event Type
{% endblock %}

{% block content %}
    <div class="row justify-content-center">

        <div class="card col-sm-10">
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    {{ form.media }}
                    {{ form| crispy }}
                    <button class="btn btn-success" type="submit"><i class="fa fa-check"></i> Submit</button>
                </form>
                <div class="mt-3">
                    <a href="{% url 'admin-portal:eventtype-list-view' %}"><i class="fa fa-arrow-left"></i> Back to List</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

src/portals/admins/templates/admins/eventtype_list.html
{% extends 'core/base.html' %}
{% load static %}

{% block base_title %} Event Types {% endblock %}
{% block page_heading %}
    Event Types
{% endblock %}

{% block base_links %}
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.22/css/jquery.dataTables.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.6.5/css/buttons.dataTables.min.css">
{% endblock %}

{% block content %}

    <div class="mb-2">
        <a href="{% url 'admin-portal:eventtype-create-view' %}" class="btn btn-primary">
            <i class="fa fa-plus"></i> Add Event Type
        </a>
    </div>

    <div class="card">
        <div class="card-body">
            {% if eventtype_list %}
                <div class="table-responsive">
                    <table class="table table-hover table-striped">
                        <thead>
                        <tr>
                            <th>ID</th>
                            <th>Name</th>
                            <th>Description</th>
                            <th>Status</th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody class="">

                        {% for row in eventtype_list %}
                            <tr>
                                <td>{{ row.pk }}</td>
                                <td>{{ row.name }}</td>
                                <td>{{ row.description }}</td>
                                <td>
                                    {% if row.is_active %}
                                        <i class="fa fa-check text-success"></i>
                                    {% else %}
                                        <i class="fa fa-times text-danger"></i>
                                    {% endif %}
                                </td>
                                <td>
                                    <a href="{% url 'admin-portal:eventtype-update-view' row.pk %}">
                                        <i class="fa fa-edit"></i></a>
                                    <a class="text-danger"
                                       href="{% url 'admin-portal:eventtype-delete-view' row.pk %}">
                                        <i class="fa fa-trash"></i></a>
                                </td>
                            </tr>

                        {% endfor %}


                        </tbody>
                    </table>
                </div>
            {% else %}
                <p>
                <h5 class="card-title text-danger">No Event Types added by administration.</h5>
                </p>

            {% endif %}
        </div>
    </div>

{% endblock %}

{% block base_internal_scripts %}

    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.5/js/dataTables.buttons.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.5/js/buttons.flash.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.5/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.5/js/buttons.print.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.5/js/buttons.colVis.min.js"></script>


{% endblock %}

{% block base_external_scripts %}
    <script>
        $(document).ready(function () {
            $('table').DataTable({
                dom: 'Bfrtip',
                buttons: [
                    {
                        extend: 'colvis',
                        exportOptions: {
                            columns: ':visible'
                        },
                        text: 'Show/Hide',
                        titleAttr: 'Column Visibility'
                    },
                    {
                        extend: 'copy',
                        exportOptions: {
                            columns: ':visible'
                        },
                        text: '<i class="fa fa-copy text-dark"></i>',
                        titleAttr: 'Copy'
                    },
                    {
                        extend: 'excel',
                        exportOptions: {
                            columns: ':visible'
                        },
                        text: '<i class="fa fa-file-excel-o text-success"></i>',
                        titleAttr: 'Excel'
                    },
                    {
                        extend: 'csv',
                        exportOptions: {
                            columns: ':visible'
                        },
                        text: '<i class="fa fa-file text-success"></i>',
                        titleAttr: 'CSV'
                    },
                    {
                        extend: 'pdf',
                        exportOptions: {
                            columns: ':visible'
                        },
                        text: '<i class="fa fa-file-pdf text-danger"></i>',
                        titleAttr: 'PDF'
                    },
                    {
                        extend: 'print',
                        exportOptions: {
                            columns: ':visible'
                        },
                        text: '<i class="fa fa-print text-primary"></i>',
                        titleAttr: 'Print'
                    }
                ]
            })
            ;

        });

    </script>
{% endblock %}

src/portals/admins/templates/admins/venue_form.html
{% extends 'core/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block base_title %}Add/Update Venue{% endblock %}

{% block page_heading %}
    Add/Update Venue
{% endblock %}

{% block content %}
    <div class="row justify-content-center">

        <div class="card col-sm-10">
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    {{ form.media }}
                    {{ form| crispy }}
                    <button class="btn btn-success" type="submit"><i class="fa fa-check"></i> Submit</button>
                </form>
                <div class="mt-3">
                    <a href="{% url 'admin-portal:venue-list-view' %}"><i class="fa fa-arrow-left"></i> Back to List</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

src/portals/admins/templates/admins/venue_list.html
{% extends 'core/base.html' %}
{% load static %}

{% block base_title %} Venues {% endblock %}
{% block page_heading %}
    Venues
{% endblock %}

{% block base_links %}
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.22/css/jquery.dataTables.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.6.5/css/buttons.dataTables.min.css">
{% endblock %}

{% block content %}

    <div class="mb-2">
        <a href="{% url 'admin-portal:venue-create-view' %}" class="btn btn-primary">
            <i class="fa fa-plus"></i> Add AddOn
        </a>
    </div>

    <div class="card">
        <div class="card-body">
            {% if venue_list %}
                <div class="table-responsive">
                    <table class="table table-hover table-striped">
                        <thead>
                        <tr>
                            <th>ID</th>
                            <th>Name</th>
                            <th>Description</th>
                            <th>Status</th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody class="">

                        {% for row in venue_list %}
                            <tr>
                                <td>{{ row.pk }}</td>
                                <td>{{ row.name }}</td>
                                <td>{{ row.price }}</td>
                                <td>
                                    {% if row.is_active %}
                                        <i class="fa fa-check text-success"></i>
                                    {% else %}
                                        <i class="fa fa-times text-danger"></i>
                                    {% endif %}
                                </td>
                                <td>
                                    <a href="{% url 'admin-portal:venue-update-view' row.pk %}">
                                        <i class="fa fa-edit"></i></a>
                                    <a class="text-danger"
                                       href="{% url 'admin-portal:venue-delete-view' row.pk %}">
                                        <i class="fa fa-trash"></i></a>
                                </td>
                            </tr>

                        {% endfor %}


                        </tbody>
                    </table>
                </div>
            {% else %}
                <p>
                <h5 class="card-title text-danger">No Venues added by administration.</h5>
                </p>

            {% endif %}
        </div>
    </div>

{% endblock %}

{% block base_internal_scripts %}

    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.5/js/dataTables.buttons.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.5/js/buttons.flash.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.5/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.5/js/buttons.print.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.5/js/buttons.colVis.min.js"></script>


{% endblock %}

{% block base_external_scripts %}
    <script>
        $(document).ready(function () {
            $('table').DataTable({
                dom: 'Bfrtip',
                buttons: [
                    {
                        extend: 'colvis',
                        exportOptions: {
                            columns: ':visible'
                        },
                        text: 'Show/Hide',
                        titleAttr: 'Column Visibility'
                    },
                    {
                        extend: 'copy',
                        exportOptions: {
                            columns: ':visible'
                        },
                        text: '<i class="fa fa-copy text-dark"></i>',
                        titleAttr: 'Copy'
                    },
                    {
                        extend: 'excel',
                        exportOptions: {
                            columns: ':visible'
                        },
                        text: '<i class="fa fa-file-excel-o text-success"></i>',
                        titleAttr: 'Excel'
                    },
                    {
                        extend: 'csv',
                        exportOptions: {
                            columns: ':visible'
                        },
                        text: '<i class="fa fa-file text-success"></i>',
                        titleAttr: 'CSV'
                    },
                    {
                        extend: 'pdf',
                        exportOptions: {
                            columns: ':visible'
                        },
                        text: '<i class="fa fa-file-pdf text-danger"></i>',
                        titleAttr: 'PDF'
                    },
                    {
                        extend: 'print',
                        exportOptions: {
                            columns: ':visible'
                        },
                        text: '<i class="fa fa-print text-primary"></i>',
                        titleAttr: 'Print'
                    }
                ]
            })
            ;

        });

    </script>
{% endblock %}